name: Criar repositorio

on: [issues]

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Criar repositorio
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/user/repos \
          -d '{"name":"repo","description":"This is your first repo!","private":false}'
